import { Category, Dish } from './dish';

// 6 - https://www.delish.com/cooking/recipe-ideas/a28691583/french-onion-mac-cheese-recipe/
// 8 - https://www.delish.com/cooking/recipe-ideas/a50009/broccoli-cheddar-soup-recipe/
// 12 - https://www.delish.com/cooking/recipe-ideas/a42805368/creamy-tuscan-orzo-recipe/
// 16 - https://www.delish.com/cooking/recipe-ideas/a35769848/oven-baked-fries-recipe/
// 17 - https://www.delish.com/cooking/recipe-ideas/a44763401/mac-and-cheese-recipe/
// 19 - https://www.delish.com/cooking/recipe-ideas/a60100015/mujaddara-recipe/
// 21 - https://www.delish.com/cooking/recipe-ideas/a46555128/marry-me-pasta-recipe/
// 25 - https://www.delish.com/cooking/recipe-ideas/a39174325/chicken-and-sausage-gumbo-recipe/
// 28 - https://www.delish.com/cooking/recipe-ideas/a42724745/monte-cristo-recipe/
// 29 - https://www.delish.com/cooking/recipe-ideas/a57949/easy-shepherds-pie-recipe/
// 31 - https://www.delish.com/cooking/recipe-ideas/a23014857/classic-stuffed-peppers-recipe/
// 32 - https://www.delish.com/cooking/recipe-ideas/a51451/easy-chicken-parmesan-recipe/
// 33 - https://www.delish.com/cooking/recipe-ideas/a46601838/french-onion-grilled-cheese-recipe/
// 37 - https://www.delish.com/cooking/recipe-ideas/a51337/classic-lasagna-recipe/
// 38 - https://www.delish.com/cooking/recipe-ideas/a60078759/vegetable-curry-recipe/
// 40 - https://www.delish.com/cooking/recipe-ideas/a32392359/chicken-katsu-recipe/
// 41 - https://www.delish.com/cooking/recipe-ideas/a25561571/deep-dish-pizza-recipe/
// 47 - https://www.delish.com/cooking/recipe-ideas/a58253/best-homemade-chili-recipe/
export const DISHES: Dish[] = [
  {
    id: '6',
    category: Category.VEGAN,
    image: '/french-onion-mac-and-cheese.avif',
    thumb: '/french-onion-mac-and-cheese.avif',
    title: 'French Onion Mac & Cheese',
    price: 18.95,
    ingredients: [
      '5 Tbsp. butter, divided, plus more room temperature for brushing',
      '2 large yellow onions, thinly sliced',
      'Kosher salt',
      '8 oz. cavatappi or other short curly pasta',
      '2 Tbsp. all-purpose flour',
      '2 1/2 cups whole milk',
      '1 cup grated fontina cheese',
      '2 1/2 cups grated Gruyère',
      '1 cup shredded sharp white cheddar',
      '1 tsp. Dijon mustard',
      'Pinch of cayenne pepper',
      '1 tsp. fresh thyme leaves, plus more for garnish',
    ],
    description:
      'French Onion Mac & Cheese is a delicious, comforting twist on the classic mac and cheese, combining the rich flavors of caramelized onions and the creamy goodness of cheese. The dish typically starts with tender elbow macaroni coated in a velvety, cheesy sauce made from a blend of melted cheeses like cheddar, Gruyère, and mozzarella.',
  },
  {
    id: '8',
    category: Category.VEGAN,
    image: '/broccoli-cheddar-soup.avif',
    thumb: '/broccoli-cheddar-soup.avif',
    title: 'Brocoli cheddar soup recipe',
    ingredients: [
      '4 Tbsp. unsalted butter',
      '1 medium yellow onion, finely chopped',
      '2 stalks celery, thinly sliced',
      '1/4 cup all-purpose flour',
      '3 cups low-sodium chicken broth',
      'Kosher salt',
      'Freshly ground black pepper',
      '1 large head broccoli, finely chopped',
      '1 large carrot, grated',
      '2 cups whole milk',
      '3 cups shredded cheddar, plus more for serving',
    ],
    price: 18.95,
    description:
      'Broccoli cheddar soup is a creamy, savory comfort food that combines tender pieces of broccoli with a velvety cheese sauce, creating a rich and satisfying bowl of goodness. The base of the soup is made from a smooth, thickened broth—often a combination of butter, flour, and milk or cream. Once the base is ready, sharp cheddar cheese is gradually melted into the mixture, transforming it into a luscious, cheesy goodness.',
  },
  {
    id: '12',
    category: Category.VEGAN,
    image: 'creamy-tuscan-orzo.avif',
    thumb: 'creamy-tuscan-orzo.avif',
    title: 'Creamy Tuscan Orzo',
    ingredients: [
      '2 Tbsp. unsalted butter',
      '12 oz. orzo',
      '4 cloves garlic, finely chopped',
      '1 Tbsp. tomato paste',
      '2 cups low-sodium vegetable or chicken broth',
      '2 cups whole milk',
      '1 cup thinly sliced sun-dried tomatoes',
      '1/2 tsp. (or more) kosher salt',
      '1/4 tsp. (or more) freshly ground black pepper',
      '4 oz. baby spinach (about 5 packed c.)',
      '1 1/2 oz. Parmesan, finely grated (about 3/4 c.), plus more for serving',
    ],
    price: 18.95,
    description:
      'Creamy Tuscan orzo is a flavorful, comforting pasta dish that combines the creamy richness of a velvety sauce with the bite-sized texture of orzo, a rice-shaped pasta. The dish typically starts with sautéed garlic, onions, and sun-dried tomatoes, which bring a burst of savory and tangy flavor to the base.',
  },
  {
    id: '16',
    category: Category.VEGAN,
    image: '/ovenbakedfries.avif',
    thumb: '/ovenbakedfries.avif',
    title: 'Oven-baked Fries',
    price: 18.95,
    ingredients: [
      '2 large russet potatoes, scrubbed clean and sliced into ⅓”-thick shoestrings',
      '2 Tbsp. extra-virgin olive oil, divided',
      'Kosher salt',
      'Freshly ground black pepper',
      'Mixed herb seasoning (optional)',
      'Ketchup, for serving',
    ],
    description:
      'Oven-baked fries are a crispy and healthier alternative to traditional deep-fried fries. They are typically made from fresh potatoes, which are cut into thin strips or wedges. The potatoes are tossed in a little olive oil and seasoned with salt, pepper, and other optional spices like garlic powder, paprika, or herbs.',
  },
  {
    id: '17',
    category: Category.PASTA,
    image: '/mac-and-cheese.avif',
    thumb: '/mac-and-cheese.avif',
    title: 'Mac and Cheese',
    price: 18.95,
    ingredients: [
      '1/2 cup (1 stick) unsalted butter, plus more for baking dish',
      'Kosher salt',
      '1 lb. elbow macaroni',
      '1/2 cup all-purpose flour',
      '5 cups whole milk',
      '1 tsp. mustard powder',
      'Freshly ground black pepper',
      '12 oz. shredded cheddar (about 3 c.)',
      '8 oz. shredded Gruyère (about 2 c.)',
      '3 oz. finely grated Parmesan (about 1 1/2 c.), divided',
      '1 cup panko bread crumbs',
      '3 Tbsp. extra-virgin olive oil',
    ],
    description:
      'Mac and cheese is a comforting and creamy dish made with cooked elbow macaroni (or other pasta shapes) and a rich cheese sauce. The sauce is typically made by melting butter and whisking in flour to create a roux, followed by adding milk (or cream) to make a smooth, velvety base. Then, shredded cheese—usually cheddar—is stirred in until melted and creamy.',
  },
  {
    id: '19',
    category: Category.VEGAN,
    image: '/mujaddara.avif',
    thumb: '/mujaddara.avif',
    title: 'Mujaddara',
    price: 18.95,
    ingredients: [
      '1 cup long-grain white rice ',
      '1 cup small green lentils ',
      '1/4 cup plus 2 tbsp. extra-virgin olive oil, divided',
      '2 large yellow onions, thinly sliced ',
      'Kosher salt',
      '1 Tbsp. cumin seeds ',
      '1 1/2 tsp. ground coriander ',
      'Pinch of ground cinnamon',
      'Torn fresh mint, for serving ',
    ],
    description:
      'Mujaddara is a flavorful and hearty Middle Eastern dish made with lentils, rice, and caramelized onions. The base consists of cooked green or brown lentils, which are combined with rice (often white or brown) and seasoned with spices such as cumin, coriander, and cinnamon, giving it a warm, aromatic flavor.',
  },
  {
    id: '21',
    category: Category.PASTA,
    image: '/marry-me-pasta-secondary.avif',
    thumb: '/marry-me-pasta-secondary.avif',
    title: 'Marry me pasta',
    price: 15.95,
    ingredients: [
      'Kosher salt',
      '1 lb. rigatoni',
      '1 Tbsp. extra-virgin olive oil',
      '3 cloves garlic, finely chopped',
      '1 Tbsp. fresh thyme leaves',
      '1/2 tsp. crushed red pepper flakes',
      '1/2 cup chopped sun-dried tomatoes',
      '3/4 cup heavy cream',
      '3/4 cup low-sodium chicken or vegetable broth',
      '1/2 cup finely grated Parmesan, plus more for serving',
      'Freshly ground black pepper',
      'Torn fresh basil, for serving',
    ],
    description:
      '"Marry Me Pasta" is a creamy, flavorful pasta dish known for its rich, indulgent taste. The dish typically features pasta (often penne or fettuccine) tossed in a luscious sauce made from heavy cream, garlic, sun-dried tomatoes, and Parmesan cheese. It’s seasoned with herbs like basil, red pepper flakes for a subtle kick, and sometimes a splash of white wine for depth.',
  },
  {
    id: '25',
    category: Category.MEET,
    image: '/cajun-chicken-sausage-gumbo.avif',
    thumb: '/cajun-chicken-sausage-gumbo.avif',
    title: 'Chicken & Sausage Gumbo',
    price: 15.95,
    ingredients: [
      '2 tsp. kosher salt',
      '1 tsp. freshly ground black pepper',
      '1 tsp. smoked paprika',
      '3/4 tsp. garlic powder',
      '1/2 tsp. mustard powder',
      '1/2 tsp. cayenne',
      '1 1/2 lb. boneless, skinless chicken thighs (about 4 thighs)',
      'Vegetable oil (1 tbsp. + 1 cup, divided)',
      '12 oz. andouille sausage, sliced into coins',
      '6 1/2 cups low-sodium chicken broth, divided',
      '1 cup all-purpose flour',
      '1 large yellow onion, finely chopped',
      '1 large green bell pepper, finely chopped',
      '2 stalks celery, finely chopped',
      '2 bay leaves',
      '4 cloves garlic, minced',
      '3 green onions, sliced (whites and greens separated)',
      '2 Tbsp. fresh thyme, chopped',
      'Steamed white rice or potato salad',
    ],
    description:
      'Gumbo is a hearty, flavorful stew that originates from Louisiana, blending influences from African, French, Spanish, and Native American cuisines. The dish typically features a rich, thick base made with a roux (a mixture of flour and fat, usually butter or oil) that is browned to give the gumbo a deep, savory flavor.',
  },
  {
    id: '28',
    category: Category.MEET,
    image: '/monte-cristo-sandwich.avif',
    thumb: '/monte-cristo-sandwich.avif',
    title: 'Monte Cristo Sandwich',
    price: 15.95,
    ingredients: [
      '2 Tbsp. unsalted butter',
      '2 large yellow onions, thinly sliced into half-moons',
      '1 tsp. kosher salt',
      '2 sprigs fresh thyme',
      '1/3 cup dry white wine',
      '8 (1/4"-thick) slices crusty country-style bread',
      '4 Tbsp. unsalted butter, softened',
      'Freshly ground black pepper',
      '2 tsp. fresh thyme leaves',
      '4 oz. Gruyère, thinly sliced',
    ],
    description:
      'A Monte Cristo sandwich is a decadent, savory-sweet creation that combines the best elements of a grilled cheese and a French toast. Typically, it\'s made by layering sliced deli meat (often ham and turkey), melted cheese (usually Swiss or Gruyère), between slices of bread. The sandwich is then dipped in an egg mixture, similar to French toast, and fried to golden, crispy perfection.',
  },
  {
    id: '29',
    category: Category.MEET,
    image: '/shepherds-pie.avif',
    thumb: '/shepherds-pie.avif',
    title: 'Shepherds Pie',
    price: 15.95,
    ingredients: [
      '2 lb. russet potatoes, peeled, sliced 1/2" thick',
      'Kosher salt',
      '2/3 cup half-and-half',
      '4 Tbsp. unsalted butter',
      '2 Tbsp. chopped fresh parsley, divided',
      'Freshly ground black pepper',
      '1 Tbsp. canola oil',
      '2 lb. lean ground beef',
      '1 medium yellow onion, chopped',
      '2 medium carrots, peeled, chopped',
      '3 cloves garlic, chopped',
      '2 tsp. chopped fresh rosemary',
      '2 tsp. chopped fresh thyme',
      '3 Tbsp. tomato paste',
      '1/2 cup dry red wine, such as Cabernet Sauvignon',
      '1 cup low-sodium beef broth',
      '3 Tbsp. Worcestershire sauce',
      'Cooking spray',
      '3 Tbsp. all-purpose flour',
      '1 cup frozen corn',
      '1 cup frozen peas',
      '3 Tbsp. grated Parmesan',
    ],
    description:
      'Shepherd’s pie is a classic, comforting dish made with a savory meat filling topped with creamy mashed potatoes. Traditionally, it’s made with ground lamb (hence the name “shepherd’s”), though in some variations, ground beef is used, and it’s then called “cottage pie.”',
  },
  {
    id: '31',
    category: Category.MEET,
    image: '/stuffed-peppers.avif',
    thumb: '/stuffed-peppers.avif',
    title: 'Stuffed Peppers',
    price: 15.95,
    ingredients: [
      '2 Tbsp. extra-virgin olive oil, plus more for drizzling',
      '1 medium yellow onion, chopped',
      '3 cloves garlic, finely chopped',
      '2 Tbsp. tomato paste',
      '1 lb. ground beef',
      '1 1/2 cups cooked white or brown rice',
      '1 (14.5-oz.) can diced tomatoes',
      '1 1/2 tsp. dried oregano',
      'Kosher salt',
      'Freshly ground black pepper',
      '6 bell peppers, tops and cores removed',
      '1 cup shredded Monterey jack',
      'Chopped fresh parsley, for serving',
    ],
    description:
      'Stuffed peppers are a flavorful and versatile dish made by filling bell peppers with a savory mixture of ingredients. The peppers are typically hollowed out, removing the seeds and membranes, and then stuffed with a combination of rice, ground meat (like beef, turkey, or chicken), vegetables, and seasonings. Sometimes, beans, cheese, or herbs are added to enhance the flavor and texture.',
  },
  {
    id: '32',
    category: Category.MEET,
    image: '/chicken-parmesan.avif',
    thumb: '/chicken-parmesan.avif',
    title: 'Chicken Parmessan',
    price: 15.95,
    ingredients: [
      '3 Tbsp. extra-virgin olive oil',
      '1 small yellow onion, finely chopped',
      '6 cloves garlic, finely chopped',
      '1 (28-oz.) can crushed tomatoes',
      '2 large sprigs basil',
      'Kosher salt',
      'Freshly ground black pepper',
      '1 cup panko bread crumbs',
      '1 tsp. garlic powder',
      '2 cups finely grated Parmesan, divided',
      '3/4 cup all-purpose flour',
      '2 large eggs',
      '6 (1/4"-thick) boneless, skinless chicken cutlets (about 1 1/2 lb. total)',
      'Kosher salt',
      'Freshly ground black pepper',
      '1 cup shredded mozzarella',
      '1 cup vegetable or canola oil',
      'Chopped fresh basil, for serving',
    ],
    description:
      'Chicken Parmesan (or Chicken Parmigiana) is a classic Italian-American dish that’s both comforting and flavorful. It typically starts with boneless, skinless chicken breasts that are breaded in a mixture of breadcrumbs and Parmesan cheese, then pan-fried until golden and crispy.',
  },
  {
    id: '33',
    category: Category.VEGAN,
    image: '/french-onion-grilled-cheese.avif',
    thumb: '/french-onion-grilled-cheese.avif',
    title: 'French Onion Grilled Cheese',
    price: 15.95,
    ingredients: [
      '2 Tbsp. unsalted butter',
      '2 large yellow onions, thinly sliced into half-moons',
      '1 tsp. kosher salt',
      '2 sprigs fresh thyme',
      '1/3 cup dry white wine',
      '8 (1/4"-thick) slices crusty country-style bread',
      '4 Tbsp. unsalted butter, softened',
      'Freshly ground black pepper',
      '2 tsp. fresh thyme leaves',
      '4 oz. Gruyère, thinly sliced',
    ],
    description:
      'A French Onion Grilled Cheese Sandwich is a savory, comforting twist on the classic grilled cheese, inspired by the flavors of French onion soup. The sandwich typically features a rich caramelized onion filling, which is sautéed until golden and sweet, then combined with melted cheese—usually a blend of Gruyère or Swiss cheese, which pairs perfectly with the onions.',
  },
  {
    id: '37',
    category: Category.PASTA,
    image: '/classic-lasagna.avif',
    thumb: '/classic-lasagna.avif',
    title: 'Lasagna',
    price: 15.95,
    ingredients: [
      '1 tsp. extra-virgin olive oil',
      '1 lb. (90% lean) ground beef',
      '1 lb. ground pork',
      '3 tbsp. tomato paste',
      '2 (32-oz.) jars marinara sauce',
      '2 tsp. kosher salt',
      '4 c. whole milk',
      '1/2 c. (1 stick) unsalted butter',
      '1/2 c. all-purpose flour',
      '1/4 tsp. ground nutmeg',
      '2 tsp. kosher salt',
      '1/2 tsp. freshly ground black pepper',
      '15 no-boil lasagna noodles (about 9 oz.)',
      '1 lb. whole-milk mozzarella, shredded',
      '3 c. finely grated Parmesan (about 7 oz.)',
      'Cooking spray',
      'Chopped fresh parsley, for serving',
    ],
    description:
      'Lasagna is a beloved Italian dish made up of layers of wide pasta sheets, savory meat sauce, creamy cheese, and often a rich béchamel sauce. The classic version features a meat sauce made from ground beef or pork, simmered with tomatoes, garlic, onions, and herbs like basil and oregano, creating a flavorful, hearty base.',
  },
  {
    id: '38',
    category: Category.VEGAN,
    image: '/vegetable-curry.avif',
    thumb: '/vegetable-curry.avif',
    title: 'Vegetable Curry',
    price: 12.95,
    ingredients: [
      '1 Tbsp. neutral oil',
      '1 medium yellow onion, thinly sliced',
      '4 cloves garlic, finely chopped',
      '1 (1") piece ginger, peeled, finely chopped',
      '3 to 4 tbsp. Thai red curry paste, or 1 (4-oz. jar) Thai Kitchen red curry paste',
      '2 (14.5-oz.) cans full-fat coconut milk',
      '1 cup low-sodium vegetable broth',
      '2 tsp. granulated sugar',
      '1 medium carrot, sliced into coins (about 1 c.)',
      '1 medium Yukon Gold potato, cut lengthwise into quarters, then sliced crosswise (about 1 c.)',
      '1 small head broccoli, cut into florets',
      '1 medium red bell pepper, seeds and ribs removed, cut into 1" pieces (about 1 c.)',
      '3 oz. green beans, halved crosswise (about 1 c.)',
      '3 Tbsp. reduced-sodium soy sauce or fish sauce (optional)',
      'Cooked rice (preferably jasmine) and fresh cilantro, for serving',
    ],
    description:
      'Vegetable curry is a flavorful and aromatic dish that combines a variety of vegetables cooked in a rich, spiced sauce. The base of the curry is usually made with onions, garlic, and ginger, sautéed to create a fragrant foundation. Then, a blend of spices like cumin, coriander, turmeric, cinnamon, and garam masala is added to give the curry its depth and warmth.',
  },
  {
    id: '40',
    category: Category.MEET,
    image: '/chicken-katsu.avif',
    thumb: '/chicken-katsu.avif',
    title: 'Kitchen Katsu',
    price: 15.95,
    ingredients: [
      '2 boneless, skinless chicken breasts',
      'Kosher salt',
      'Freshly ground black pepper',
      '2/3 cup all-purpose flour',
      '2 large eggs',
      '1 1/4 cups panko breadcrumbs',
      'Vegetable oil, for frying',
      '1/2 cup ketchup',
      '1 1/2 Tbsp. soy sauce ',
      '1 Tbsp. Worcestershire sauce',
      '2 tsp. rice wine vinegar',
      '1 tsp. Dijon mustard',
    ],
    description:
      'Chicken Katsu is a popular Japanese dish consisting of breaded and deep-fried chicken cutlets, typically served with a side of rice, shredded cabbage, and a tangy, savory sauce. The chicken breast or thigh is first seasoned, then dipped in flour, followed by a coat of beaten egg, and finally coated in panko breadcrumbs, which give it a light, crispy texture when fried.',
  },
  {
    id: '41',
    category: Category.PASTA,
    image: '/deep-dish.avif',
    thumb: '/deep-dish.avif',
    title: 'Deep-Dish Pizza',
    price: 15.95,
    ingredients: [
      '2 3/4 cups (330 g.) all-purpose flour',
      '1/3 cup (52.5 g.) stone-ground cornmeal',
      '1 (1/4-oz.) packet instant yeast',
      '1 Tbsp. kosher salt ',
      '1 Tbsp. granulated sugar ',
      '1/2 cup (1 sticks) unsalted butter, softened, divided ',
      '4 Tbsp. extra-virgin olive oil, divided',
      '1 lb. sweet Italian sausage ',
      '1 medium yellow onion, finely chopped',
      '5 cloves garlic, coarsely chopped',
      '1/2 tsp. dried basil',
      '1/2 tsp. garlic powder',
      '1/4 tsp. dried oregano',
      '1 1/2 tsp. kosher salt, divided  ',
      '1 (28-oz.) can crushed tomatoes ',
      'All-purpose flour, for dusting',
      '12 oz. mozzarella, shredded',
      'Finely grated Parmesan, for serving',
    ],
    description:
      'Deep dish pizza is a hearty and indulgent style of pizza that originated in Chicago. Unlike traditional thin-crust pizzas, deep dish features a thick, buttery crust that lines the pan, forming a "pie" that’s loaded with a rich, flavorful filling. The crust is typically baked until golden and crispy, providing a sturdy base to hold the layers of toppings.',
  },
  {
    id: '47',
    category: Category.MEET,
    image: '/chili.avif',
    thumb: '/chili.avif',
    title: 'Chili',
    price: 15.95,
    ingredients: [
      '1 Tbsp. extra-virgin olive oil',
      '1/2 large white onion, chopped',
      '3 cloves garlic, finely chopped',
      '2 Tbsp. tomato paste',
      '1 1/2 lb. ground beef',
      '1 1/2 Tbsp. chili powder',
      '1 tsp. dried oregano',
      '1 tsp. ground cumin',
      '1/2 tsp. paprika',
      '1/4 tsp. cayenne pepper (optional)',
      'Kosher salt',
      'Freshly ground black pepper',
      '1 (28-oz.) can crushed tomatoes',
      '1 (15-oz.) can kidney beans, drained',
      'Shredded cheddar, sour cream, and sliced scallions, for serving',
    ],
    description:
      'Chili is a hearty, flavorful stew that typically combines ground meat (like beef, turkey, or pork) with beans, tomatoes, and a variety of spices. The dish is known for its bold and spicy flavor, with ingredients such as chili powder, cumin, garlic, onions, and paprika creating a rich base.',
  },
];
